# Generated by Django 4.2.19 on 2025-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del solicitante')),
                ('direccion', models.TextField(verbose_name='Dirección del contacto')),
                ('celular', models.TextField(verbose_name='Telefono de contacto')),
            ],
        ),
    ]
