# Generated by Django 4.2.19 on 2025-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.ManyToManyField(to='pedidos.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
