# Generated by Django 4.2.19 on 2025-03-05 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_producto_pedido_pedidos_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
